"""
PLN Analytics Platform — FastAPI Application Entry Point

Run locally:
    uvicorn app.main:app --reload

Production:
    uvicorn app.main:app --host 0.0.0.0 --port $PORT
"""

from __future__ import annotations

import logging

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.core.config import get_settings
from app.core.logging_config import configure_logging
from app.interface.api.v1.router import api_v1_router

settings = get_settings()

configure_logging(settings.DEBUG)
logger = logging.getLogger(__name__)

app = FastAPI(
    title=settings.APP_NAME,
    description=(
        "Enterprise Analytics Platform for PLN.\n\n"
        "Modules:\n"
        "- Upload Center\n"
        "- Executive Dashboard\n"
        "- DLPD Monitoring\n"
        "- Suspect Analytics\n"
        "- Warehouse Management\n\n"
        "The API never reads raw Excel directly. "
        "All dashboard endpoints consume processed datasets "
        "generated by the ETL Engine."
    ),
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
    openapi_url="/openapi.json",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ==========================================================
# API ROUTES
# ==========================================================

app.include_router(api_v1_router)

# ==========================================================
# HEALTH CHECK
# ==========================================================

@app.get(
    "/health",
    tags=["Health"],
)
def health_check():

    return {
        "status": "ok",
        "application": settings.APP_NAME,
        "environment": settings.ENVIRONMENT,
    }


# ==========================================================
# STARTUP
# ==========================================================

@app.on_event("startup")
def on_startup():

    logger.info("=" * 80)
    logger.info("%s", settings.APP_NAME)
    logger.info("Environment : %s", settings.ENVIRONMENT)
    logger.info("Processed Data : %s", settings.DATA_PROCESSED_DIR)

    if not settings.DATA_PROCESSED_DIR.exists():

        logger.warning(
            "Processed data directory not found. "
            "Run the ETL pipeline before accessing dashboard endpoints."
        )

    logger.info("=" * 80)